// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnWNesf5a_J3jzpMdvOUSJtNG7QTdXXLI',
    appId: '1:474833026756:web:1a3fc69400712050201391',
    messagingSenderId: '474833026756',
    projectId: 'food-diary-ca61c',
    authDomain: 'food-diary-ca61c.firebaseapp.com',
    storageBucket: 'food-diary-ca61c.appspot.com',
    measurementId: 'G-ZMBZT5W3MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcJWe45nbx5JPji6FyouZ3ele-bgyj_BU',
    appId: '1:474833026756:android:3cdc5d7a651fa3be201391',
    messagingSenderId: '474833026756',
    projectId: 'food-diary-ca61c',
    storageBucket: 'food-diary-ca61c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZuTDeprY9cgspdD98Zx47r4SdG9A27hY',
    appId: '1:474833026756:ios:2fb3541fa961b378201391',
    messagingSenderId: '474833026756',
    projectId: 'food-diary-ca61c',
    storageBucket: 'food-diary-ca61c.appspot.com',
    iosBundleId: 'com.example.gemeniFoodDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZuTDeprY9cgspdD98Zx47r4SdG9A27hY',
    appId: '1:474833026756:ios:2fb3541fa961b378201391',
    messagingSenderId: '474833026756',
    projectId: 'food-diary-ca61c',
    storageBucket: 'food-diary-ca61c.appspot.com',
    iosBundleId: 'com.example.gemeniFoodDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnWNesf5a_J3jzpMdvOUSJtNG7QTdXXLI',
    appId: '1:474833026756:web:c0e322bf8eae1a49201391',
    messagingSenderId: '474833026756',
    projectId: 'food-diary-ca61c',
    authDomain: 'food-diary-ca61c.firebaseapp.com',
    storageBucket: 'food-diary-ca61c.appspot.com',
    measurementId: 'G-LQ7B8WGLSR',
  );
}
